import { type Character } from "./types";

export const DEFAULT_CHARACTERS: Character[] = [
    {
        character_id: "confucius",
        name: "孔子",
        isChineseHistorical: true,
        region: "中国",
        era: "古代",
        roles: ["思想家", "教育家"],
        tags: ["儒家", "春秋", "经典"],
        summary: "春秋时期思想家和教育家，儒家学派的重要代表。",
        name_en: "Confucius",
        region_en: "China",
        era_en: "Antiquity",
        roles_en: ["Philosopher", "Educator"],
        tags_en: ["Confucianism", "Spring and Autumn period", "Classics"],
        summary_en: "A philosopher and educator of the Spring and Autumn period and a key figure of Confucianism.",
    },
    {
        character_id: "qin-shi-huang",
        name: "秦始皇",
        isChineseHistorical: true,
        region: "中国",
        era: "古代",
        roles: ["帝王", "政治家"],
        tags: ["统一", "秦朝", "中央集权"],
        summary: "完成中国历史上重要统一的秦朝皇帝，推行郡县制和统一制度。",
        name_en: "Qin Shi Huang",
        region_en: "China",
        era_en: "Antiquity",
        roles_en: ["Emperor", "Statesman"],
        tags_en: ["Unification", "Qin dynasty", "Centralization"],
        summary_en: "First emperor of Qin who unified China and established centralized imperial institutions.",
    },
    {
        character_id: "emperor-wu-han",
        name: "汉武帝",
        isChineseHistorical: true,
        region: "中国",
        era: "古代",
        roles: ["帝王", "政治家"],
        tags: ["汉朝", "丝绸之路", "儒学"],
        summary: "西汉皇帝，扩展疆域并推动儒学成为重要政治思想。",
        name_en: "Emperor Wu of Han",
        region_en: "China",
        era_en: "Antiquity",
        roles_en: ["Emperor", "Statesman"],
        tags_en: ["Han dynasty", "Silk Road", "Confucianism"],
        summary_en: "Han emperor who expanded Chinese territory and institutionalized Confucianism in government.",
    },
    {
        character_id: "li-bai",
        name: "李白",
        isChineseHistorical: true,
        region: "中国",
        era: "古代",
        roles: ["诗人", "文学家"],
        tags: ["唐朝", "诗歌", "浪漫"],
        summary: "唐代著名诗人，以豪放想象和浪漫诗风闻名。",
        name_en: "Li Bai",
        region_en: "China",
        era_en: "Ancient",
        roles_en: ["Poet", "Writer"],
        tags_en: ["Tang dynasty", "Poetry", "Romantic style"],
        summary_en: "Great Tang poet famous for grand imagination and lyrical, romantic style.",
    },
    {
        character_id: "wu-zetian",
        name: "武则天",
        isChineseHistorical: true,
        region: "中国",
        era: "古代",
        roles: ["帝王", "政治家"],
        tags: ["唐朝", "女性统治者", "周"],
        summary: "中国历史上重要的女性统治者，曾建立武周政权。",
        name_en: "Wu Zetian",
        region_en: "China",
        era_en: "Ancient",
        roles_en: ["Emperor", "Stateswoman"],
        tags_en: ["Tang dynasty", "Female ruler", "Zhou"],
        summary_en: "A major female ruler in Chinese history who established the Zhou dynasty period of her reign.",
    },
    {
        character_id: "yue-fei",
        name: "岳飞",
        isChineseHistorical: true,
        region: "中国",
        era: "古代",
        roles: ["军事人物", "民族英雄"],
        tags: ["南宋", "抗金", "忠义"],
        summary: "南宋将领，以抗金事迹和忠义形象广为人知。",
        name_en: "Yue Fei",
        region_en: "China",
        era_en: "Ancient",
        roles_en: ["Military leader", "National hero"],
        tags_en: ["Southern Song", "Resistance against Jurchens", "Loyalty"],
        summary_en: "A Song dynasty general famous for resistance against the Jurchen-led Jin and a symbol of loyalty.",
    },
    {
        character_id: "genghis-khan",
        name: "成吉思汗",
        region: "蒙古草原",
        era: "古代",
        roles: ["军事人物", "统治者"],
        tags: ["蒙古帝国", "征服", "草原"],
        summary: "蒙古帝国奠基者，统一蒙古诸部并发动大规模扩张。",
        name_en: "Genghis Khan",
        region_en: "Mongolian Steppe",
        era_en: "Ancient",
        roles_en: ["Military leader", "Ruler"],
        tags_en: ["Mongol Empire", "Conquest", "Steppe"],
        summary_en: "Founder of the Mongol Empire who unified steppe tribes and launched wide conquests.",
    },
    {
        character_id: "zheng-he",
        name: "郑和",
        isChineseHistorical: true,
        region: "中国",
        era: "古代",
        roles: ["航海家", "外交人物"],
        tags: ["明朝", "远航", "海上交流"],
        summary: "明代航海家，率船队多次远航，推动海上交流。",
        name_en: "Zheng He",
        region_en: "China",
        era_en: "Ancient",
        roles_en: ["Explorer", "Diplomat"],
        tags_en: ["Ming dynasty", "Maritime expeditions", "Oceanic exchange"],
        summary_en: "Ming dynasty admiral who led treasure fleets on major maritime voyages.",
    },
    {
        character_id: "kangxi-emperor",
        name: "康熙",
        isChineseHistorical: true,
        region: "中国",
        era: "近世",
        roles: ["帝王", "政治家"],
        tags: ["清朝", "治理", "盛世"],
        summary: "清朝皇帝，在位时间很长，参与巩固疆域和国家治理。",
        name_en: "Emperor Kangxi",
        region_en: "China",
        era_en: "Early modern",
        roles_en: ["Emperor", "Statesman"],
        tags_en: ["Qing dynasty", "Governance", "Prosperous era"],
        summary_en: "A long-reigning Qing emperor who stabilized territory and governance during a major dynasty.",
    },
    {
        character_id: "empress-dowager-cixi",
        name: "慈禧",
        isChineseHistorical: true,
        region: "中国",
        era: "近现代",
        roles: ["政治人物", "皇室成员"],
        tags: ["清朝", "晚清", "垂帘听政"],
        summary: "晚清重要政治人物，长期影响清朝最高决策。",
        name_en: "Empress Dowager Cixi",
        region_en: "China",
        era_en: "Modern",
        roles_en: ["Political leader", "Royal figure"],
        tags_en: ["Qing dynasty", "Late Qing", "De facto ruler"],
        summary_en: "A dominant late Qing political figure who exerted major influence over imperial decisions for decades.",
    },
    {
        character_id: "sun-yat-sen",
        name: "孙中山",
        isChineseHistorical: true,
        region: "中国",
        era: "近现代",
        roles: ["革命家", "政治家"],
        tags: ["辛亥革命", "共和", "三民主义"],
        summary: "近代中国革命家和政治家，推动共和思想和政治变革。",
        name_en: "Sun Yat-sen",
        region_en: "China",
        era_en: "Modern",
        roles_en: ["Revolutionary", "Politician"],
        tags_en: ["Xinhai Revolution", "Republic", "Three Principles of the People"],
        summary_en: "Revolutionary and politician in late imperial China who advocated republican ideals and political reform.",
    },
    {
        character_id: "lu-xun",
        name: "鲁迅",
        isChineseHistorical: true,
        region: "中国",
        era: "近现代",
        roles: ["文学家", "思想家"],
        tags: ["现代文学", "批判", "小说"],
        summary: "中国现代文学重要作家，以小说和杂文影响深远。",
        name_en: "Lu Xun",
        region_en: "China",
        era_en: "Modern",
        roles_en: ["Writer", "Essayist"],
        tags_en: ["Modern Chinese literature", "Criticism", "Novels"],
        summary_en: "A leading modern Chinese writer whose fiction and essays heavily influenced 20th century thought.",
    },
    {
        character_id: "alexander-the-great",
        name: "亚历山大大帝",
        region: "欧洲",
        era: "古代",
        roles: ["军事人物", "统治者"],
        tags: ["马其顿", "征服", "希腊化"],
        summary: "马其顿国王，建立横跨欧亚非的帝国并推动希腊化影响。",
        name_en: "Alexander the Great",
        region_en: "Europe",
        era_en: "Antiquity",
        roles_en: ["Military leader", "Ruler"],
        tags_en: ["Macedonia", "Conquest", "Hellenistic influence"],
        summary_en: "King of Macedonia whose conquests created an empire spanning Eurasia and Africa.",
    },
    {
        character_id: "julius-caesar",
        name: "凯撒",
        region: "欧洲",
        era: "古代",
        roles: ["政治家", "军事人物"],
        tags: ["罗马", "共和国", "独裁官"],
        summary: "古罗马政治家和军事统帅，对罗马共和国末期局势影响巨大。",
        name_en: "Julius Caesar",
        region_en: "Europe",
        era_en: "Antiquity",
        roles_en: ["Politician", "Military commander"],
        tags_en: ["Rome", "Republic", "Dictator"],
        summary_en: "Roman statesman and general whose career transformed the late Republic.",
    },
    {
        character_id: "napoleon",
        name: "拿破仑",
        region: "欧洲",
        era: "近现代",
        roles: ["军事人物", "帝王"],
        tags: ["法国", "战争", "法典"],
        summary: "法国军事统帅和皇帝，重塑欧洲政治格局并留下法典影响。",
        name_en: "Napoleon Bonaparte",
        region_en: "Europe",
        era_en: "Modern",
        roles_en: ["Military commander", "Emperor"],
        tags_en: ["France", "Wars", "Napoleonic Code"],
        summary_en: "French emperor and commander who reshaped European politics and legacy through the Napoleonic Code.",
    },
    {
        character_id: "abraham-lincoln",
        name: "林肯",
        region: "美洲",
        era: "近现代",
        roles: ["政治家", "总统"],
        tags: ["美国", "内战", "废奴"],
        summary: "美国总统，领导南北战争时期的联邦并推动废除奴隶制。",
        name_en: "Abraham Lincoln",
        region_en: "North America",
        era_en: "Modern",
        roles_en: ["Politician", "President"],
        tags_en: ["United States", "Civil War", "Emancipation"],
        summary_en: "U.S. president during the Civil War era who preserved the Union and advanced emancipation.",
    },
    {
        character_id: "william-shakespeare",
        name: "莎士比亚",
        region: "欧洲",
        era: "近世",
        roles: ["剧作家", "文学家"],
        tags: ["英国", "戏剧", "十四行诗"],
        summary: "英国剧作家和诗人，作品包括多部影响深远的戏剧。",
        name_en: "William Shakespeare",
        region_en: "Europe",
        era_en: "Early modern",
        roles_en: ["Playwright", "Poet"],
        tags_en: ["Britain", "Drama", "Poetry"],
        summary_en: "English playwright and poet whose works have shaped world literature for centuries.",
    },
    {
        character_id: "leonardo-da-vinci",
        name: "达芬奇",
        region: "欧洲",
        era: "近世",
        roles: ["艺术家", "发明家"],
        tags: ["文艺复兴", "绘画", "科学探索"],
        summary: "文艺复兴时期艺术家和博学者，以绘画和科学手稿闻名。",
        name_en: "Leonardo da Vinci",
        region_en: "Europe",
        era_en: "Renaissance",
        roles_en: ["Artist", "Inventor"],
        tags_en: ["Renaissance", "Painting", "Scientific exploration"],
        summary_en: "Renaissance artist and polymath known for masterpieces and scientific notebooks.",
    },
    {
        character_id: "isaac-newton",
        name: "牛顿",
        region: "欧洲",
        era: "近世",
        roles: ["科学家", "数学家"],
        tags: ["物理", "万有引力", "经典力学"],
        summary: "英国科学家和数学家，建立经典力学的重要基础。",
        name_en: "Isaac Newton",
        region_en: "Europe",
        era_en: "Modern",
        roles_en: ["Scientist", "Mathematician"],
        tags_en: ["Physics", "Gravity", "Classical mechanics"],
        summary_en: "English physicist and mathematician who established the foundations of classical mechanics.",
    },
    {
        character_id: "marie-curie",
        name: "居里夫人",
        region: "欧洲",
        era: "近现代",
        roles: ["科学家"],
        tags: ["放射性", "诺贝尔奖", "化学"],
        summary: "物理学家和化学家，因放射性研究获得重要科学成就。",
        name_en: "Marie Curie",
        region_en: "Europe",
        era_en: "Modern",
        roles_en: ["Scientist"],
        tags_en: ["Radioactivity", "Nobel Prize", "Chemistry"],
        summary_en: "Physicist and chemist who made landmark discoveries in radioactivity and won Nobel Prizes.",
    },
    {
        character_id: "albert-einstein",
        name: "爱因斯坦",
        region: "欧洲",
        era: "现代",
        roles: ["科学家"],
        tags: ["相对论", "物理", "诺贝尔奖"],
        summary: "理论物理学家，提出相对论并深刻影响现代物理。",
        name_en: "Albert Einstein",
        region_en: "Europe",
        era_en: "Modern",
        roles_en: ["Scientist"],
        tags_en: ["Relativity", "Physics", "Nobel Prize"],
        summary_en: "Theoretical physicist who proposed relativity and transformed modern scientific thinking.",
    },
    {
        character_id: "mahatma-gandhi",
        name: "甘地",
        region: "印度",
        era: "现代",
        roles: ["政治领袖", "社会运动家"],
        tags: ["非暴力", "印度独立", "公民抗争"],
        summary: "印度独立运动领袖，以非暴力抵抗思想和实践闻名。",
        name_en: "Mahatma Gandhi",
        region_en: "India",
        era_en: "Modern",
        roles_en: ["Political leader", "Civil rights activist"],
        tags_en: ["Non-violence", "Indian independence", "Civil resistance"],
        summary_en: "Leader of India's independence movement, known for principled non-violent resistance.",
    },
    {
        character_id: "nelson-mandela",
        name: "曼德拉",
        region: "非洲",
        era: "现代",
        roles: ["政治领袖", "总统"],
        tags: ["南非", "反种族隔离", "和解"],
        summary: "南非政治领袖和总统，长期反对种族隔离制度。",
        name_en: "Nelson Mandela",
        region_en: "Africa",
        era_en: "Modern",
        roles_en: ["Political leader", "President"],
        tags_en: ["South Africa", "Anti-apartheid", "Reconciliation"],
        summary_en: "South African leader and president known for opposing apartheid and guiding national reconciliation.",
    },
    {
        character_id: "martin-luther-king-jr",
        name: "马丁·路德·金",
        region: "美洲",
        era: "现代",
        roles: ["社会运动家", "牧师"],
        tags: ["美国", "民权运动", "非暴力"],
        summary: "美国民权运动领袖，倡导非暴力抗争和平等权利。",
        name_en: "Martin Luther King Jr.",
        region_en: "North America",
        era_en: "Modern",
        roles_en: ["Civil rights leader", "Minister"],
        tags_en: ["United States", "Civil Rights Movement", "Non-violence"],
        summary_en: "American civil rights leader known for peaceful resistance and struggle for equality.",
    },
];
