import { type Character } from "./types";

export const DEFAULT_CHARACTERS: Character[] = [
    {
        character_id: "confucius",
        name: "孔子",
        region: "中国",
        era: "古代",
        roles: ["思想家", "教育家"],
        tags: ["儒家", "春秋", "经典"],
        summary: "春秋时期思想家和教育家，儒家学派的重要代表。",
    },
    {
        character_id: "qin-shi-huang",
        name: "秦始皇",
        region: "中国",
        era: "古代",
        roles: ["帝王", "政治家"],
        tags: ["统一", "秦朝", "中央集权"],
        summary: "完成中国历史上重要统一的秦朝皇帝，推行郡县制和统一制度。",
    },
    {
        character_id: "emperor-wu-han",
        name: "汉武帝",
        region: "中国",
        era: "古代",
        roles: ["帝王", "政治家"],
        tags: ["汉朝", "丝绸之路", "儒学"],
        summary: "西汉皇帝，扩展疆域并推动儒学成为重要政治思想。",
    },
    {
        character_id: "li-bai",
        name: "李白",
        region: "中国",
        era: "古代",
        roles: ["诗人", "文学家"],
        tags: ["唐朝", "诗歌", "浪漫"],
        summary: "唐代著名诗人，以豪放想象和浪漫诗风闻名。",
    },
    {
        character_id: "wu-zetian",
        name: "武则天",
        region: "中国",
        era: "古代",
        roles: ["帝王", "政治家"],
        tags: ["唐朝", "女性统治者", "周"],
        summary: "中国历史上重要的女性统治者，曾建立武周政权。",
    },
    {
        character_id: "yue-fei",
        name: "岳飞",
        region: "中国",
        era: "古代",
        roles: ["军事人物", "民族英雄"],
        tags: ["南宋", "抗金", "忠义"],
        summary: "南宋将领，以抗金事迹和忠义形象广为人知。",
    },
    {
        character_id: "genghis-khan",
        name: "成吉思汗",
        region: "蒙古草原",
        era: "古代",
        roles: ["军事人物", "统治者"],
        tags: ["蒙古帝国", "征服", "草原"],
        summary: "蒙古帝国奠基者，统一蒙古诸部并发动大规模扩张。",
    },
    {
        character_id: "zheng-he",
        name: "郑和",
        region: "中国",
        era: "古代",
        roles: ["航海家", "外交人物"],
        tags: ["明朝", "远航", "海上交流"],
        summary: "明代航海家，率船队多次远航，推动海上交流。",
    },
    {
        character_id: "kangxi-emperor",
        name: "康熙",
        region: "中国",
        era: "近世",
        roles: ["帝王", "政治家"],
        tags: ["清朝", "治理", "盛世"],
        summary: "清朝皇帝，在位时间很长，参与巩固疆域和国家治理。",
    },
    {
        character_id: "empress-dowager-cixi",
        name: "慈禧",
        region: "中国",
        era: "近现代",
        roles: ["政治人物", "皇室成员"],
        tags: ["清朝", "晚清", "垂帘听政"],
        summary: "晚清重要政治人物，长期影响清朝最高决策。",
    },
    {
        character_id: "sun-yat-sen",
        name: "孙中山",
        region: "中国",
        era: "近现代",
        roles: ["革命家", "政治家"],
        tags: ["辛亥革命", "共和", "三民主义"],
        summary: "近代中国革命家和政治家，推动共和思想和政治变革。",
    },
    {
        character_id: "lu-xun",
        name: "鲁迅",
        region: "中国",
        era: "近现代",
        roles: ["文学家", "思想家"],
        tags: ["现代文学", "批判", "小说"],
        summary: "中国现代文学重要作家，以小说和杂文影响深远。",
    },
    {
        character_id: "alexander-the-great",
        name: "亚历山大大帝",
        region: "欧洲",
        era: "古代",
        roles: ["军事人物", "统治者"],
        tags: ["马其顿", "征服", "希腊化"],
        summary: "马其顿国王，建立横跨欧亚非的帝国并推动希腊化影响。",
    },
    {
        character_id: "julius-caesar",
        name: "凯撒",
        region: "欧洲",
        era: "古代",
        roles: ["政治家", "军事人物"],
        tags: ["罗马", "共和国", "独裁官"],
        summary: "古罗马政治家和军事统帅，对罗马共和国末期局势影响巨大。",
    },
    {
        character_id: "napoleon",
        name: "拿破仑",
        region: "欧洲",
        era: "近现代",
        roles: ["军事人物", "帝王"],
        tags: ["法国", "战争", "法典"],
        summary: "法国军事统帅和皇帝，重塑欧洲政治格局并留下法典影响。",
    },
    {
        character_id: "abraham-lincoln",
        name: "林肯",
        region: "美洲",
        era: "近现代",
        roles: ["政治家", "总统"],
        tags: ["美国", "内战", "废奴"],
        summary: "美国总统，领导南北战争时期的联邦并推动废除奴隶制。",
    },
    {
        character_id: "william-shakespeare",
        name: "莎士比亚",
        region: "欧洲",
        era: "近世",
        roles: ["剧作家", "文学家"],
        tags: ["英国", "戏剧", "十四行诗"],
        summary: "英国剧作家和诗人，作品包括多部影响深远的戏剧。",
    },
    {
        character_id: "leonardo-da-vinci",
        name: "达芬奇",
        region: "欧洲",
        era: "近世",
        roles: ["艺术家", "发明家"],
        tags: ["文艺复兴", "绘画", "科学探索"],
        summary: "文艺复兴时期艺术家和博学者，以绘画和科学手稿闻名。",
    },
    {
        character_id: "isaac-newton",
        name: "牛顿",
        region: "欧洲",
        era: "近世",
        roles: ["科学家", "数学家"],
        tags: ["物理", "万有引力", "经典力学"],
        summary: "英国科学家和数学家，建立经典力学的重要基础。",
    },
    {
        character_id: "marie-curie",
        name: "居里夫人",
        region: "欧洲",
        era: "近现代",
        roles: ["科学家"],
        tags: ["放射性", "诺贝尔奖", "化学"],
        summary: "物理学家和化学家，因放射性研究获得重要科学成就。",
    },
    {
        character_id: "albert-einstein",
        name: "爱因斯坦",
        region: "欧洲",
        era: "现代",
        roles: ["科学家"],
        tags: ["相对论", "物理", "诺贝尔奖"],
        summary: "理论物理学家，提出相对论并深刻影响现代物理。",
    },
    {
        character_id: "mahatma-gandhi",
        name: "甘地",
        region: "印度",
        era: "现代",
        roles: ["政治领袖", "社会运动家"],
        tags: ["非暴力", "印度独立", "公民抗争"],
        summary: "印度独立运动领袖，以非暴力抵抗思想和实践闻名。",
    },
    {
        character_id: "nelson-mandela",
        name: "曼德拉",
        region: "非洲",
        era: "现代",
        roles: ["政治领袖", "总统"],
        tags: ["南非", "反种族隔离", "和解"],
        summary: "南非政治领袖和总统，长期反对种族隔离制度。",
    },
    {
        character_id: "martin-luther-king-jr",
        name: "马丁·路德·金",
        region: "美洲",
        era: "现代",
        roles: ["社会运动家", "牧师"],
        tags: ["美国", "民权运动", "非暴力"],
        summary: "美国民权运动领袖，倡导非暴力抗争和平等权利。",
    },
];
